stages:
  - build

before_script:
  - IMAGE_VERSION=${CI_COMMIT_SHORT_SHA}

dockerize:
  stage: build
  script:
    - IMAGE_NAME="kube-green"
    # Authenticate with gcr.io
    - docker login -u _json_key -p "$(echo $GCR_SA_JSON | base64 -d)" https://gcr.io &>/dev/null
    - docker login -u _json_key -p "$(echo $GCR_SA_JSON | base64 -d)" https://asia.gcr.io &>/dev/null
    # Docker build with BUILDKIT
    - docker build
      --tag  $GCR_URL/$IMAGE_NAME:$IMAGE_VERSION
      --file Dockerfile
      "."
    - docker image tag  $GCR_URL/$IMAGE_NAME:$IMAGE_VERSION  $GCR_URL/$IMAGE_NAME:latest
    # Docker push finally
    - docker push $GCR_URL/$IMAGE_NAME:$IMAGE_VERSION
    - docker push $GCR_URL/$IMAGE_NAME:latest
